name: Run Azure CLI Login with OpenID Connect

on:
  workflow_dispatch:  # Enables manual trigger only

jobs:
  test:
    permissions:
      id-token: write # Required for OIDC token

    runs-on: ubuntu-latest

    steps:
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
