name: Run Azure Login With a Service Principal Secret

on:
  workflow_dispatch:
permissions:
  id-token: write
  issues: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login (Service Principal Secret)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show --output table
